### ISSUE TITLE
After Action Report

### ISSUE THREAD

**Issue by ZAJohan** [recce-gaming/recce-missions#9]
AAR -A3 as suggested by TheMagnetar. We need the following stats:
1. Opfor killed by Blufor.
2. Blufor players killed.
3. Blufor friendly kills.
4. *If we can: There will be x amount of hostile AI "Command" units. Can we tell with this how many of them were killed?

**Comment by adampiskorski** [comment]
We would use an off the shelf AAR on the server side, so nothing to do with the mission itself or this repo.
I don't think any of the AAR systems allow you to have custom counters. Best would just be to save that to the log and use the AAR system for everything else.

**Comment by ZAJohan** [comment]
Thanks Phoenix. Will you please guide me through what I need to do?

**Comment by adampiskorski** [comment]
It's something I will need to implement on the server side.
Our servers are ephemeral, so linking to a cloud partition would probably be the best bet.
I can make a small script that you can add to a unit that has it log itself when it's dead like the current player death log does.

**Comment by adampiskorski** [comment]
This issue will be closed with the logging to file, as the AAR doesn't go into this code base.

**Comment by adampiskorski** [comment]
To mark enemy commanders or any other special unit for counting in the log, add this to their init:
```sqf
this setVariable ["is_special", true];
```

**Comment by adampiskorski** [comment]
I've had a change of plans regarding the AAR system.
There are 3 that I looked at:
* https://github.com/CntoDev/CNTR: Requires a server side mod and direct access to web server and custom file format.
* https://github.com/alexcroox/R3: Rquires server side mod and MySQL DB and server tied to it
* https://github.com/10Dozen/tS_AARViewer: Requires a small modification of the mission and writes to the existing rpt file

The first 2 options are suited for a website that is always on and on the same box as the server with all missions having their AARs immediately available.
The first one could write it's aar file and not be read by a web server, though you will need to set one up to view it offline.

The third option gives you one file for everything, the rpt file that we are already managing. You take the file into a converter, convert it to an AAR file and view it, and you can use a freely available web site to do that privately (without uploading any AAR data): http://taw-arma.github.io/tS_AARViewer/
I think that the third option also suits an ephemeral server like how our international work better
CNTR is a close second, but the third one is much easier to set up and management is simpler
So it turns out that the AAR viewer (for the third option) is part of the mission now and nothing to do with the server setup, so the opposite of what I said (this is the first AAR software for that), for this one at least
